source 'https://bitbucket.org/kishykumar/yibbypods'
source 'https://github.com/ello/cocoapod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
project '../YibbyPartner'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
end

def shared_pods
    pod 'Alamofire'
    pod 'GoogleMaps'
    pod 'Google/CloudMessaging'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'BaasBoxSDK’
    pod 'SwiftyJSON'
    pod 'MMDrawerController'
    pod 'TTRangeSlider'
    pod 'BButton'
    pod 'MBProgressHUD'
    pod 'TextFieldEffects'
    pod 'CocoaLumberjack/Swift'
    pod 'LaunchScreen'
    pod 'NVActivityIndicatorView'
    pod 'OpenInGoogleMaps'
    pod 'Fabric'
    pod 'Crashlytics'
    #pod 'JTCalendar', '~> 2.0'
    pod 'JTCalendar'
    pod 'ISHPullUp'
    #pod 'XLPagerTabStrip', '~> 6.0'
    pod 'XLPagerTabStrip'
    pod 'SwiftKeychainWrapper'
    pod 'ActionSheetPicker-3.0'
    pod 'IQKeyboardManagerSwift'
    pod 'AlamofireObjectMapper'
    #pod 'AIFlatSwitch', '~> 1.0.1'
    pod 'AIFlatSwitch'
    #pod 'DGRunkeeperSwitch', '~> 1.1.4'
    pod 'DGRunkeeperSwitch'
    pod 'ImagePicker'
    pod 'Lightbox'
    pod 'FoldingCell'
    
    #pod 'Font-Awesome-Swift', '~> 1.6.2'
    pod 'Font-Awesome-Swift'
    pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
    pod 'PhoneNumberKit'
    pod 'Presentr'
    pod 'Cosmos'
    pod 'AMPopTip'
    #pod 'CRToast', '~> 0.0.7'
    pod 'LTMorphingLabel'
    pod 'M13ProgressSuite'
    pod 'DZNEmptyDataSet'
    
    pod 'PINRemoteImage'
    pod 'Braintree'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'Google/SignIn'
    pod 'AccountKit'
    
end

target 'YibbyPartner' do
    shared_pods
end

target 'YibbyPartnerTests' do
    shared_pods
    testing_pods
end

post_install do |installer|
    #installer.pods_project.targets.each do |target|
    #    target.build_configurations.each do |config|
    #        config.build_settings['SWIFT_VERSION'] = '3.0'
    #    end
    #end
    
    installer.pods_project.targets.each do |target|
        if ['DGRunkeeperSwitch'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
    
    puts("Update debug pod settings to speed up build time")
    Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
    end
end


